### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by yuejiejiayou** [QiangCai/opencv-java-face-recognition#1]
您好，我运行Recognition.java出现以下错误：
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.face.LBPHFaceRecognizer.create_1()J
	at org.opencv.face.LBPHFaceRecognizer.create_1(Native Method)
	at org.opencv.face.LBPHFaceRecognizer.create(LBPHFaceRecognizer.java:54)
	at face.recognize.Recognition.main(Recognition.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by QiangCai** [comment]
opencv版本是一致的吗？

**Comment by yuejiejiayou** [comment]
大神：
          您好，很高兴得到您的回复，是版本不一致导致的，现在问题已经解决，感谢。另外想就以下的问题再向你请教：
截图是Recognition.java中的代码片段，confidence是人脸比对后的置信度，我再测试的时候这个值的范围基本在30-150之间，根据网上资料这个值越小说明匹配度越高，是同一个人的几率越大。我想问的是这个值能有什么算法将它转换成百分比的相似度吗，或者您的这部分代码有所优化吗，期待您的回复！


he_yj89@163.com
 
发件人： david
发送时间： 2019-04-25 12:19
收件人： QiangCai/opencv-java-face-recognition
抄送： yuejiejiayou; Author
主题： Re: [QiangCai/opencv-java-face-recognition] 运行出错 (#1)
opencv版本是一致的吗？

**Comment by QiangCai** [comment]
这个值可以类比为距离，越小越相近。 后续还没计划，可以考虑使用深度学习方法。

**Comment by MaaiMohsen** [comment]
How the attached problem was solved?

**Comment by QiangCai** [comment]
need use openCV version 3.4.1

**Comment by yuejiejiayou** [comment]
ok，thank you!



he_yj89@163.com
 
发件人： david
发送时间： 2019-05-09 15:07
收件人： QiangCai/opencv-java-face-recognition
抄送： yuejiejiayou; Author
主题： Re: [QiangCai/opencv-java-face-recognition] 运行出错 (#1)
need use openCV version 3.4.1

**Comment by MaaiMohsen** [comment]
I can't find dll files for open CV 3.4.1 contributed , This is my issue. Is there any way to solve this problem?

**Comment by yuejiejiayou** [comment]
@MaaiMohsen What is your development environment?

**Comment by MaaiMohsen** [comment]
Iam using Netbeans 8.1 IDE

**Comment by yuejiejiayou** [comment]
window or mac?

**Comment by yuejiejiayou** [comment]
windows or mac?

**Comment by MaaiMohsen** [comment]
Windows

**Comment by yuejiejiayou** [comment]
I have dll files for open CV 3.4.0 contributed, Currently working properly。

**Comment by yuejiejiayou** [comment]
https://blog.csdn.net/u013841196/article/details/85040644，Please refer to this tutorial

**Comment by karunarathana** [comment]
> [https://blog.csdn.net/u013841196/article/details/85040644，Please](https://blog.csdn.net/u013841196/article/details/85040644%EF%BC%8CPlease) refer to this tutorial

Can you send me the file?please
